# coding=utf-8
from django.conf.urls import url

from polls import student, manager, teacher
from . import views

urlpatterns = [
    # 定义访问页面和登录注册页面
    url(r'^$', views.index, name='index'),
    url(r'^manager/$', views.manager),
    url(r'^student/$', views.student),
    url(r'^teacher/$', views.teacher),
    url(r'^manager/login/$', manager.login),
    url(r'^student/login/$', student.login),
    url(r'^teacher/login/$', teacher.login),

    # manager 相关操作
    url(r'^manager/index/$', manager.index),
    url(r'^manager/student/$', manager.student),
    url(r'^manager/student/add/$', manager.studentAdd),
    url(r'^manager/student/submit/$', manager.studentSubmit),
    url(r'^manager/student/info/$', manager.studentInfo),
    url(r'^manager/student/modify/$', manager.stuModify),
    url(r'^manager/student/modCaG/$', manager.stuModCaG),
    url(r'^manager/student/search/$', manager.stuSearch),
    url(r'^manager/stuCou/delete/$', manager.stuCouDel),
    url(r'^manager/stuGro/add/$', manager.groupStuAdd),
    url(r'^manager/stuGro/del/$', manager.groupStuDel),
    url(r'^manager/teacher/$', manager.teacher),
    url(r'^manager/teacher/add/$', manager.teacherAdd),
    url(r'^manager/teacher/submit/$', manager.teacherSubmit),
    url(r'^manager/teacher/info/$', manager.teacherInfo),
    url(r'^manager/teacher/modify/$', manager.teaModify),
    url(r'^manager/teacher/modCaG/$', manager.teaModCaG),
    url(r'^manager/course/$', manager.course),
    url(r'^manager/course/add/$', manager.courseAdd),
    url(r'^manager/course/submit/$', manager.courseSubmit),
    url(r'^manager/course/info/$', manager.courseInfo),
    url(r'^manager/course/modify/$', manager.courseModify),
    url(r'^manager/academy/$', manager.academy),
    url(r'^manager/academyInfo/$', manager.academyInfo),
    url(r'^manager/academy/add/$', manager.academyAdd),
    url(r'^manager/academy/submit/$', manager.academySubmit),
    url(r'^manager/academy/delete/$', manager.academyDel),
    url(r'^manager/major/$', manager.major),
    url(r'^manager/major/add/$', manager.majorAdd),
    url(r'^manager/major/submit/$', manager.majorSubmit),
    url(r'^manager/major/delete/$', manager.majorDel),
    url(r'^manager/group/search/$', manager.groupSearch),

    # student 相关操作
    url(r'^student/register/$', student.register),
    url(r'^student/register/submit/$', student.registerSubmit),
    url(r'^student/index/$', student.index),
    url(r'^student/course/$', student.course),
    url(r'^student/courseInfo/$', student.courseInfo),
    url(r'^student/mycourse/$', student.mycourse),
    url(r'^student/addcourse/$', student.addcourse),
    url(r'^student/couSearch/$', student.couSearch),
    url(r'^student/removecourse/$', student.removecourse),
    url(r'^student/group/$', student.group),
    url(r'^student/mygroup/$', student.mygroup),
    url(r'^student/groupInfo/$', student.groupInfo),
    url(r'^student/groupadd/$', student.groupadd),
    url(r'^student/groupquit/$', student.groupquit),
    url(r'^student/schedule/$', student.schedule),
    url(r'^student/information/$', student.information),
    url(r'^student/information/detail/$', student.infoDetail),
    url(r'^student/myself/$', student.myself),
    url(r'^student/sendmsg/$', student.sendmsg),
    url(r'^student/sendmsg/submit/$', student.sendmsgSubmit),
    url(r'^student/(?P<course_id>[0-9]+)/index/$', student.courseIndex),
    url(r'^student/(?P<course_id>[0-9]+)/schedule/$', student.courseSchedule),
    url(r'^student/(?P<course_id>[0-9]+)/notice/$', student.courseNotice),
    url(r'^student/(?P<course_id>[0-9]+)/namelist/$', student.courseNamelist),
    # url(r'^student/(?P<course_id>[0-9]+)/resource/$', student.courseResource),
    url(r'^student/(?P<course_id>[0-9]+)/download/$', student.courseDownload),
    url(r'^student/(?P<course_id>[0-9]+)/chat/$', student.courseChat),
    url(r'^student/(?P<course_id>[0-9]+)/group/$', student.courseGroups),
    url(r'^student/(?P<course_id>[0-9]+)/sendmsg/$', student.courseSendmsg),
    url(r'^student/(?P<course_id>[0-9]+)/msgsubmit/$', student.courseMsgsubmit),
    url(r'^student/(?P<course_id>[0-9]+)/homework/$', student.courseHomework),
    url(r'^student/(?P<course_id>[0-9]+)/hwDetail/$', student.courseHwDetail),
    url(r'^student/(?P<course_id>[0-9]+)/cgDetail/$', student.courseCgDetail),
    url(r'^student/quit/$', student.quit),

    # teacher 相关操作
    url(r'^teacher/register/$', teacher.register),
    url(r'^teacher/register/submit/$', teacher.registerSubmit),
    url(r'^teacher/index/$', teacher.index),
    url(r'^teacher/mycourse/$', teacher.mycourse),
    url(r'^teacher/courseInfo/$', teacher.courseInfo),
    url(r'^teacher/mygroup/$', teacher.mygroup),
    url(r'^teacher/groupInfo/$', teacher.groupInfo),
    url(r'^teacher/group/create/$', teacher.groupCreate),
    url(r'^teacher/deleteStu/$', teacher.deleteStu),
    url(r'^teacher/information/$', teacher.information),
    url(r'^teacher/information/detail/$', teacher.infoDetail),
    url(r'^teacher/infoResponse/$', teacher.infoResponse),
    url(r'^teacher/sendmsg/$', teacher.sendmsg),
    url(r'^teacher/sendmsg/submit/$', teacher.sendmsgSubmit),
    url(r'^teacher/search/$', teacher.search),
    url(r'^teacher/broadcast/$', teacher.broadcast),
    url(r'^teacher/quit/$', teacher.quit),
]